### ISSUE TITLE
Nixus is easy to confuse with NixOS

### ISSUE THREAD

**Issue by Mic92** [Infinisil/nixus#14]
When using the word in conversation is quite easy to confuse `Nixus` with `NixOS` as it only differs in one vocal. It might be also not a great term for search engines this way.
(came up yesterday in a NixOS mumble meetup when talking about nixus)

**Comment by Infinisil** [comment]
I don't intend to change the name for now, since there already was a name change before (see https://github.com/Infinisil/nixus/issues/1). I don't think this is a big problem really, more so because NixOS is written with two capital letters and has a different tonation because of it. I'll keep this in mind though, maybe there can be another name change when this isn't experimental anymore.
