### ISSUE TITLE
error: set : Option '-o' inconnue

### ISSUE THREAD

**Issue by bbigras** [Infinisil/nixus#16]
Sorry for the French error. The script doesn't seem to respect `LANG=c`.

I wonder if this is caused because I'm using the fish shell.

also I might not be using any secrets right now. I'm just testing.

```
[desktop] Connecting to host...
[desktop] Copying closure to host...
[desktop] Copying secrets...
[desktop] set : Option '-o' inconnue
[desktop] 
[desktop] Entrée standard (line 1): 
[desktop] set -o noglob; sudo rsync --server -pe.LsfxC --usermap=*:root --groupmap=*:root . /var/lib/nixus-secrets/pending/included-secrets
[desktop] ^
[desktop] 
[desktop] (Type 'help set' for related documentation)
[desktop] fish: Pas de correspondance pour le joker '--usermap=*:root'. Lisez `help expand`.
[desktop] set -o noglob; sudo rsync --server -pe.LsfxC --usermap=*:root --groupmap=*:root . /var/lib/nixus-secrets/pending/included-secrets
[desktop]                                              ^
[desktop] rsync: connection unexpectedly closed (0 bytes received so far) [sender]
[desktop] rsync error: remote shell failed (code 124) at io.c(226) [sender=3.1.3]
```

EDIT: I don't seem to have the problem if I switch to bash.

**Comment by Infinisil** [comment]
Ah darn, this is caused by https://github.com/Infinisil/nixus/blob/7ea1a7806ebf3c98eab282a94a0f2bd337932f11/modules/secrets.nix#L189

The `set -o noglob` is necessary because using `--rsync-path` calls rsync using the remote hosts shell, but the `--chown "root:root"` option in also transformed into `--usermap=*:root`, which when passed to the shell would expand to all files in the users home directory, which is not correct of course. So the error one gets without the `set -o noglob` when the remote shell is zsh or bash is
```
zsh:1: no matches found: --usermap=*:root
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]
```

I'll try to see about not using `--chown` so we don't have to rely on `set -o noglob`

**Comment by bbigras** [comment]
> You can also specify any remote shell you like, either by using the -e
command line option, or by setting the RSYNC_RSH environment variable.

Would forcing bash help?

**Comment by Infinisil** [comment]
Oh that would be an alternative, I just fixed the issue by not using `--chown` on master, see https://github.com/Infinisil/nixus/commit/489df2a7b16248553145ce664dc9735b26233c7d. Does that work for you?

**Comment by bbigras** [comment]
It seems fine. Thank you very much.

**Comment by Infinisil** [comment]
And thank _you_ for the bug report :)
