### ISSUE TITLE
Any strategy for sensitive stuff with nixus and cachix?

### ISSUE THREAD

**Issue by bbigras** [Infinisil/nixus#18]
I have a private git repo for my config stuff and it's awesome.

I would love to have a public one like [lovesegfault's](https://github.com/lovesegfault/nix-config) with a free public cachix cache and github actions but there's stuff in my nix config that I would like to avoid being public like ssh hosts, spotify password...

I think I could normally use git-crypt but I think my "secret" stuff would still end up in the cachix cache.

Any user of nixus have already thought about this problem?

**Comment by Infinisil** [comment]
The [secret module](https://github.com/Infinisil/nixus/blob/master/modules/secrets.nix) doesn't put secrets in the Nix store, meaning they also won't end up on cachix. But of course you still need to store the secret files somewhere in the git repo with this.

I personally use a [private git submodule](https://github.com/Infinisil/system/blob/eb1046aa55802989ac8baffc8f476a5e3a682451/.gitmodules#L4-L6) for this, which contains all the files I don't want to be public in cleartext.

I haven't used git-crypt before, but it should also work without problems.

Alternatively, I recently found out about https://github.com/Mic92/sops-nix, which you could also use with Nixus (it only relies on a NixOS config) independently of the Nixus secret module.

**Comment by bbigras** [comment]
Is the secret module only for files? Can it be used to add extra hosts to my `programs.ssh`?

Also, I'm wondering if the secret module would work with CI like github actions. lovesegfault seems to stub his secrets. I'm guessing to make them build on the CI.

For things like `programs.ssh`,  I'm guessing that maybe if there would be a way to import a nix file only if it exists, I could do that.

**Comment by Infinisil** [comment]
> Is the secret module only for files? Can it be used to add extra hosts to my `programs.ssh`?

The secret module is for sensitive files that should never end up in `/nix/store` (and therefore a Nix cache). It allows you to specify where the secret files are located during the Nix evaluation. Then you can freely refer to these secrets from any hosts. All secrets that the host refers to will be copied to the host so it can access them (and deleted if it doesn't need them anymore). The example directory shows how the secret module can be used: https://github.com/Infinisil/nixus/blob/103742baf0bd10b51780efdf91fac8ac50a7fa32/example/configuration.nix#L29-L31

This can't be used for NixOS options, for one because all NixOS option assignments end up in `/nix/store`, and also because the secrets values can only be accessed during runtime (this is actually a consequence of the former reason).

If you just want to hide some Nix expressions from a public repo (and you don't care that the values end up in `/nix/store`), you can just hide those expressions any way you like, e.g. with a private git submodule as suggested above. The NixOS module system is very modular, and Nixus takes advantage of that. Specifically you can use `imports` from a toplevel Nixus config to import another file very much like it. This is how I import all my secret code: https://github.com/Infinisil/system/blob/eb1046aa55802989ac8baffc8f476a5e3a682451/deploy/default.nix#L31-L33

> Also, I'm wondering if the secret module would work with CI like github actions. lovesegfault seems to stub his secrets. I'm guessing to make them build on the CI.

Yeah I think stubbing secrets is the best way to do this for now. Maybe there's gonna be something better for this in the future though.

**Comment by bbigras** [comment]
> If you just want to hide some Nix expressions from a public repo (and you don't care that the values end up in /nix/store or a Nix cache), you can just hide those expressions any way you like, e.g. with a private git submodule as suggested above. The NixOS module system is very modular, and Nixus takes advantage of that. Specifically you can use imports from a toplevel Nixus config to import another file very much like it, allowing you to split the whole config however you like. This is how I import all my secret code: https://github.com/Infinisil/system/blob/eb1046aa55802989ac8baffc8f476a5e3a682451/deploy/default.nix#L31-L33.

Any way to stub that import or only import if the file exists? To make it work with CI.

**Comment by Infinisil** [comment]
Could do
```nix
{
  imports = if builtins.pathExists ./secret-config.nix then [ ./secret-config.nix ] else [];
}
```

Similar to how lovesegfault's [mkSecret](https://github.com/lovesegfault/nix-config/blob/a1b00c1dc5dca245758efd1b2dc61a3b69a33e42/overlays/mkSecret.nix) works

**Comment by bbigras** [comment]
Sorry for the late reply.

This works perfectly.

Thank you very much!
